In [24]:
import pandas as pd

# De praxe, carregamos o arquivo csv usando panda e definimos inicialmente o dataframe como df
df = pd.read_csv('SICOR_CONTRATOS_MUNICIPIO_2020_BRUTO.csv', header=0, sep=';', engine='python', on_bad_lines='skip', encoding='latin-1')

## ANALISE DOS DADOS FILTRADO POR ESTADO (CE)

In [25]:
# Aqui nos apenas estamos filtrando o dataframe para aparecer somente os dados do estado do ceara, assim descartando os demais por não ser no nosso interesse
df_filtrado_CE_2020 = df[df['nomeUF'] == 'CE']
df_filtrado_CE_2020.to_csv('df_filtrado_CE_2020.csv', index=False)
display(df_filtrado_CE_2020.iloc[1:6])  # Exibe as linhas de 1 a 5 do dataframe filtrado para o estado do Ceará

,#cdEstado,nomeUF,cdMunicipio,codMunicIbge,Municipio,MesEmissao,AnoEmissao,cdPrograma,cdSubPrograma,cdFonteRecurso,...,QtdInvestimento,VlInvestimento,QtdComercializacao,VlComercializacao,QtdIndustrializacao,VlIndustrializacao,AreaInvestimento,AreaCusteio,cnpjIF,nomeIF
402,6,CE,44901,2308377.0,MIRAï¿½MA,11,2020,1,56,502,...,3,10000.0,0,0.0,0,0.0,0.0,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
444,6,CE,19929,2309904.0,PACUJï¿½,9,2020,1,56,502,...,11,36500.0,0,0.0,0,0.0,0.0,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
456,6,CE,34863,2304400.0,FORTALEZA,10,2020,999,0,201,...,0,0.0,0,0.0,1,1500000.0,0.0,0.0,60701190,BCO ITAU S.A.
671,6,CE,10894,2307700.0,MARANGUAPE,4,2020,999,0,201,...,0,0.0,0,0.0,2,2000000.0,0.0,0.0,90400888,BCO MERIDIONAL DO BRASIL S.A.
766,6,CE,11594,2302305.0,BELA CRUZ,12,2020,1,56,502,...,8,19070.0,0,0.0,0,0.0,3.0,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.

## ANALISE COM FILTRO DO CEARA + PRONAF (COD = 1)

In [26]:
df_filtrado_CE_2020_cod_pronaf = df_filtrado_CE_2020[df_filtrado_CE_2020['cdPrograma'] == 1]
display(df_filtrado_CE_2020_cod_pronaf.iloc[1:6])  # Exibe as linhas de 1 a 5 do dataframe filtrado para o estado do Ceará
df_filtrado_CE_2020_cod_pronaf.to_csv('df_filtrado_CE_2020_cod_pronaf.csv', index=False)

,#cdEstado,nomeUF,cdMunicipio,codMunicIbge,Municipio,MesEmissao,AnoEmissao,cdPrograma,cdSubPrograma,cdFonteRecurso,...,QtdInvestimento,VlInvestimento,QtdComercializacao,VlComercializacao,QtdIndustrializacao,VlIndustrializacao,AreaInvestimento,AreaCusteio,cnpjIF,nomeIF
402,6,CE,44901,2308377.0,MIRAï¿½MA,11,2020,1,56,502,...,3,10000.00,0,0.0,0,0.0,0.00,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
444,6,CE,19929,2309904.0,PACUJï¿½,9,2020,1,56,502,...,11,36500.00,0,0.0,0,0.0,0.00,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
766,6,CE,11594,2302305.0,BELA CRUZ,12,2020,1,56,502,...,8,19070.00,0,0.0,0,0.0,3.00,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
891,6,CE,24653,2305407.0,ICï¿½,1,2020,1,2,502,...,1,4233.00,0,0.0,0,0.0,0.00,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.
918,6,CE,43407,2304277.0,ERERï¿½,9,2020,1,5,502,...,3,27695.18,0,0.0,0,0.0,1.11,0.0,7237373,BCO DO NORDESTE DO BRASIL S.A.